### ISSUE TITLE
Undo feature

### ISSUE THREAD

**Issue by rostopira** [ricardodalarme/flutter_card_swiper#1]
I would like to have a method like undo in `CardSwiperController`

**Comment by marcusrohden** [comment]
hi @ricardodalarme, do you have any prediction on when this feature will be released?
thanks

**Comment by ricardodalarme** [comment]
There is a draft #4 that is almost finished. I just need some time to work on the details. I'll try to have a look at it this weekend. Does that sound good to you?

**Comment by ricardodalarme** [comment]
Released in version 4.1.0 😉
