### ISSUE TITLE
Customizing back card offset position

### ISSUE THREAD

**Issue by farkmu45** [ricardodalarme/flutter_card_swiper#11]
So I recently started using this package, pretty neat!! However I have a use case where the card is positioned exactly on top of each other (so kinda like a stack of cards where the 2nd card is covered completely with the 1st card). Looking at the docs, there's no option to customize the back card offset position, is there anyway to do this?

**Comment by ricardodalarme** [comment]
Hmmm, that doesn't feel hard. I just opened a draft PR addressing this issue, can you check if it matches what you want?

- https://github.com/ricardodalarme/flutter_card_swiper/pull/12
