### ISSUE TITLE
Unable to import the package 

### ISSUE THREAD

**Issue by akksel1** [ricardodalarme/flutter_card_swiper#19]
Hey ! 

I can't import this package in my project ...

I've added `flutter_card_swiper: ^5.0.0` inside the dependencies in my projet's pubspec.yalm file. 

And when I try to import the package in my DART file (`import 'package:flutter_card_swiper/flutter_card_swiper.dart';`) it says : Target of URI doesn't exist: 'package:flutter_card_swiper/flutter_card_swiper.dart'.
Try creating the file referenced by the URI, or try using a URI for a file that does exist.dart[uri_does_not_exist](https://dart.dev/diagnostics/uri_does_not_exist).

Any idea how to solve it ?

**Comment by ricardodalarme** [comment]
Are u sure you ran `flutter pub get`?
