### ISSUE TITLE
onSwipe returns wrong resulting index

### ISSUE THREAD

**Issue by lagif** [ricardodalarme/flutter_card_swiper#7]
After checking closely I see that the onSwipe index  after first crd swipe is still 0, and all following swipes return lower values. 
This may happen because the ` widget.onSwipe?.call(_currentIndex, detectedDirection);` called BEFORE the index is updated, not AFTER.

**Comment by ricardodalarme** [comment]
Thank you for reporting this issue! It was fixed on the last release
