### ISSUE TITLE
Adding new cards to the stack on-the-fly

### ISSUE THREAD

**Issue by simplenotezy** [ricardodalarme/flutter_card_swiper#8]
Came from https://github.com/appinioGmbH/flutter_packages and stumbled upon your package here, and reviewed a bit of your code. Looks like some decent improvements!

I like that you added internal state of cards  - as well as seperated the package into it's own, which it deserves - however, do you have any working examples of adding new cards to the stack? E.g. when there's 3 items left in stack, add in more?

**Comment by ricardodalarme** [comment]
Well, at the moment I don't have any examples of this, or any plans to include it in the package. However, yesterday I released a new version that replaces the old `cards` param with a builder function, and I also added an `initialIndex` param. So you may be able to do what you want with these new parameters. If it doesn't work, feel free to open a PR on this issue.

**Comment by j3g** [comment]
Hello. I am banging my head on how to implement infinite swiping. There aren't enough details here for me to figure it out. I am currently using Notify / Consumer in an attempt to rebuild the CardSwiper widget when the cards are getting near the end. Tinder and other apps do an infinite scrolling.
